select 
fpo.customer_id	     as fpo_customer_id 	,			
fpo.employee_id	     as fpo_employee_id	,			
fpo.purchase_order_id ,					
fpo.product_id		 as fpo_product_id	,		
fpo.quantity			,	
fpo.unit_cost			,	
fpo.date_received		,			
fpo.posted_to_inventory	,			
fpo.inventory_id		,			
fpo.supplier_id			,		
fpo.created_by		,
fpo.submitted_date	,			
fpo.creation_date	,			
fpo.status_id		,		
fpo.expected_date	,			
fpo.shipping_fee	,				
fpo.taxes			,		
fpo.payment_date	,				
fpo.payment_amount	,				
fpo.payment_method	,				
fpo.notes			,		
fpo.approved_by	,				
fpo.approved_date ,				
fpo.submitted_by	,	
dp.product_id , 
dp.product_code,
dp.product_name ,
dp.description ,
dp.company , 
dp.standard_cost , 
dp.list_price , 
dp.reorder_level , 
dp.target_level , 
dp.quantity_per_unit ,
dp.discontinued,
dp.minimum_reorder_quantity ,
dp.category ,
dp.attachments ,
dc.customer_id , 
dc.company  as customer_company ,
dc.first_name  as customer_first_name, 
dc.last_name as customer_last_name,
dc.email_address as customer_email_address,
dc.job_title as customer_job_title ,
dc.business_phone as customer_business_phone ,
dc.mobile_phone  as customer_mobile_phone ,
dc.home_phone  as customer_home_phone, 
dc.fax_number  as customer_fax_number,
dc.address  as customer_address, 
dc.city  as customer_city , 
dc.state_province  as customer_state_province, 
dc.zip_postal_code as customer_zip_postal_code, 
dc.country_region  as customer_country_region, 
dc.web_page  as customer_web_page, 
dc.notes  as customer_notes, 
dc.attachments as customer_attachments,
de.employee_id ,
de.company  e_company,
de.first_name as e_first_name , 
de.last_name  as e_last_name,
de.email_address as e_email_address,
de.job_title as e_job_title,
de.business_phone as e_business_phone ,
de.mobile_phone as e_mobile_phone ,
de.home_phone  as e_home_phone, 
de.fax_number  as e_fax_number,
de.address as e_address , 
de.city  as e_city, 
de.state_province as  e_state_province, 
de.zip_postal_code  as e_zip_postal_code , 
de.country_region as e_country_region , 
de.web_page  as e_web_page , 
de.notes  as e_notes, 
de.attachments as e_attachments


from {{ ref ('fact_purchase_order')}} fpo 
left join {{ ref ('dim_customer')}} dc
on fpo.customer_id = dc.customer_id
left join {{ ref ('dim_product')}} dp
on fpo.product_id  = dp.product_id
left join {{ ref ('dim_employee')}} de
on fpo.employee_id = de.employee_id 

